name: Build, Test, and Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Create build directory
      run: |
        if [ -d build ]; then
          rm -rf build
        fi
        mkdir build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure -C Debug -T test

    - name: Verify main executable
      run: |
        cd build
        ./ConceptualExample

    - name: Verify test executable
      run: |
        cd build
        ./runTests

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Executables
        path: |
          build/ConceptualExample
          build/runTests
